In [ ]:
import torch
import os
import numpy as np
from google.colab import drive
drive.mount('/content/drive')
DATA_DIR='/content/drive/MyDrive/Colab Notebooks/mesh2matrix/BIR_Workshop/model_mesh'
#DATA_DIR='/content/drive/MyDrive/BIR_Workshop/model_mesh'
PATH=os.path.join(DATA_DIR,'best_model_1')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
os.chdir('/content/drive/MyDrive/Colab Notebooks/mesh2matrix')

In [ ]:
!pip install -r MeSH2Matrix/requirements.txt

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 2.3 MB 10.3 MB/s 
     |████████████████████████████████| 804.1 MB 2.4 kB/s 
     |████████████████████████████████| 7.1 MB 30.3 MB/s 
     |████████████████████████████████| 793 kB 51.3 MB/s 
     |████████████████████████████████| 381 kB 55.6 MB/s 
  Attempting uninstall: prompt-toolkit
    Found existing installation: prompt-toolkit 1.0.18
    Uninstalling prompt-toolkit-1.0.18:
      Successfully uninstalled prompt-toolkit-1.0.18
  Attempting uninstall: torch
    Found existing installation: torch 1.11.0+cu113
    Uninstalling torch-1.11.0+cu113:
      Successfully uninstalled torch-1.11.0+cu113
  Attempting uninstall: ipython
    Found existing installation: ipython 5.5.0
    Uninstalling ipython-5.5.0:
      Successfully uninstalled ipython-5.5.0
  Attempting uninstall: torchtext
    Found existing installation: torchtext 0.12.0
    Uninstalli

In [ ]:
from google.colab import drive
import os
import matplotlib.pyplot as plt
import pandas as pd
import torch
import numpy as np
from sklearn.model_selection import train_test_split
import torchtext
from torch.utils.data import Dataset,DataLoader
from torchtext.legacy.data import Field, TabularDataset, BucketIterator, Iterator
import torch.nn as nn
from torch.nn.utils.rnn import pack_padded_sequence, pad_packed_sequence
import torch.optim as optim
import torch.nn.functional as F
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score

from sklearn.metrics import classification_report as cr

device = torch.device('cuda' if True and torch.cuda.is_available() else 'cpu')

NUM_CLASSES = 195
BATCH_SIZE = 32

In [ ]:
class MESHDataset(Dataset):
    def __init__(self,numpy_file,label_file):
     
      try:
        self.data= np.load(numpy_file)
        self.labels = np.load(label_file)
      except Exception as err:
        raise Exception(f'ERROR OPENING FILES: {numpy_file} | {label_file}. See Error below. \n {err}')  
       
    def __len__(self):
        return self.data.shape[0]
    def __getitem__(self, idx):
        #Get the element with `idx`
        #Output an 89*89 matrix
        return self.data[idx].flatten(), self.labels[idx]

In [ ]:
test_dataset = MESHDataset(os.path.join(DATA_DIR,'test.npy'),os.path.join(DATA_DIR,'test_labels.npy'))
# test_dataset = MESHDataset(os.path.join(DATA_DIR,'test.npy'),os.path.join(DATA_DIR,'grouped_test_labels.npy'))
test_dataloader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False)

In [ ]:
from sklearn.metrics import accuracy_score
def compute_accuracy(pred, target):
  return target.detach().numpy(), pred.argmax(-1).detach().numpy()

In [ ]:
class BaselineModel(nn.Module):

    def __init__(self, matrix_size=89):
        super(BaselineModel, self).__init__()
        self.linear1 = nn.Linear(matrix_size**2, (matrix_size**2)//2)
        self.linear2 = nn.Linear((matrix_size**2)//2, matrix_size**2//4)
        self.linear3 = nn.Linear((matrix_size**2)//4, NUM_CLASSES)
        
    def forward(self, x):

        x = self.linear1(x)
        x = F.relu(x) 

        x = self.linear2(x)
        x = F.relu(x)

        x = self.linear3(x)
        return x

In [ ]:
model = BaselineModel().to(device)
model.load_state_dict(torch.load(PATH, map_location='cpu'))
print(model)
model.eval()

labels, preds = [], []
for test_features, test_label in test_dataloader:
  # print(test_features.size())
  test_features, test_label = test_features.to(device), test_label.to(device)
  test_pred = model(test_features.float())
  true, predictions = compute_accuracy(test_pred.cpu(),test_label.cpu())
  labels += true.tolist()
  preds += predictions.tolist()
print(f'Best Dense Model Accuracy with 195 classes:{accuracy_score(labels, preds)}')
print("Best Dense Model Weighted F1-Score with 195 classes: {}".format(f1_score(labels, preds, average='weighted')))

BaselineModel(
  (linear1): Linear(in_features=7921, out_features=3960, bias=True)
  (linear2): Linear(in_features=3960, out_features=1980, bias=True)
  (linear3): Linear(in_features=1980, out_features=195, bias=True)
)
Best Dense Model Accuracy with 195 classes:0.7077684527652249
Best Dense Model Weighted F1-Score with 195 classes: 0.6689272084790814


# Confusion Matrix

In [ ]:
list(set(preds)) in list(set(labels))

False

In [ ]:
len(set(preds))

56

In [ ]:
len(set(labels))

125

In [ ]:
confusion= confusion_matrix(labels, preds)
print(confusion)

[[  0   0   0 ...   2   0   0]
 [  0  54   0 ...   0   0   0]
 [  0   0   1 ...   0   0   0]
 ...
 [  0   0   0 ... 267   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]
